// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqttkcywgvlhzstpczac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxdHRrY3l3Z3ZsaHpzdHBjemFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MzgyODUsImV4cCI6MjA2NTExNDI4NX0.pEbZYW5vcQiraUSFAJKq2veEqklOdjUcS20Dy-rr8gQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);